"""Example 1: GitHub Actions CI/CD Integration

This example shows how to integrate AIOps with GitHub Actions for automated code review.
"""

import asyncio
import os
from pathlib import Path
from aiops.agents.code_reviewer import CodeReviewAgent
from aiops.agents.security_scanner import SecurityScannerAgent
from aiops.agents.test_generator import TestGeneratorAgent


async def review_pull_request():
    """Review a pull request using AIOps agents."""

    # Get PR information from environment variables
    pr_files = os.getenv("PR_FILES", "").split(",")
    pr_number = os.getenv("PR_NUMBER", "unknown")

    print(f"📋 Reviewing PR #{pr_number}")
    print(f"📁 Files to review: {len(pr_files)}")

    # Initialize agents
    code_reviewer = CodeReviewAgent()
    security_scanner = SecurityScannerAgent()
    test_generator = TestGeneratorAgent()

    review_results = []
    security_issues = []
    missing_tests = []

    for file_path in pr_files:
        if not file_path.strip():
            continue

        print(f"\n🔍 Analyzing: {file_path}")

        # Read file content
        try:
            with open(file_path, 'r') as f:
                code = f.read()
        except Exception as e:
            print(f"⚠️  Could not read {file_path}: {e}")
            continue

        # Determine language
        language = Path(file_path).suffix.lstrip('.')

        # 1. Code Review
        print(f"  → Running code review...")
        review = await code_reviewer.execute(code=code, language=language)
        review_results.append({
            "file": file_path,
            "score": review.overall_score,
            "issues": len(review.issues),
            "critical": sum(1 for i in review.issues if i.severity == "critical"),
        })

        # 2. Security Scan
        print(f"  → Scanning for security issues...")
        security = await security_scanner.execute(code=code, language=language)
        if security.critical_count > 0 or security.high_count > 0:
            security_issues.append({
                "file": file_path,
                "critical": security.critical_count,
                "high": security.high_count,
                "risk_score": security.risk_score,
            })

        # 3. Check for tests
        if "test_" not in file_path and language == "py":
            print(f"  → Checking test coverage...")
            tests = await test_generator.execute(
                code=code,
                language=language,
                test_type="unit"
            )
            if tests.total_tests == 0:
                missing_tests.append(file_path)

    # Generate summary
    print("\n" + "="*60)
    print("📊 REVIEW SUMMARY")
    print("="*60)

    # Overall scores
    if review_results:
        avg_score = sum(r["score"] for r in review_results) / len(review_results)
        total_issues = sum(r["issues"] for r in review_results)
        critical_issues = sum(r["critical"] for r in review_results)

        print(f"\n✅ Average Code Quality Score: {avg_score:.1f}/100")
        print(f"⚠️  Total Issues Found: {total_issues}")
        print(f"🚨 Critical Issues: {critical_issues}")

    # Security summary
    if security_issues:
        print(f"\n🔒 SECURITY ISSUES:")
        for issue in security_issues:
            print(f"  - {issue['file']}: "
                  f"{issue['critical']} critical, "
                  f"{issue['high']} high "
                  f"(risk score: {issue['risk_score']:.0f})")
    else:
        print(f"\n✅ No critical security issues found")

    # Test coverage
    if missing_tests:
        print(f"\n🧪 FILES WITHOUT TESTS:")
        for file in missing_tests:
            print(f"  - {file}")

    # Determine if PR should be approved
    should_approve = (
        critical_issues == 0 and
        len(security_issues) == 0 and
        avg_score >= 70
    )

    if should_approve:
        print("\n✅ PR APPROVED - All checks passed!")
        return 0
    else:
        print("\n❌ PR NEEDS WORK - Please address the issues above")
        return 1


async def post_review_comment():
    """Post review results as a GitHub comment."""

    # This would use GitHub API to post comments
    # For example:
    comment = """
## 🤖 AIOps Automated Review

### Code Quality
- Average Score: 85/100
- Issues Found: 5 (0 critical, 3 medium, 2 low)

### Security Scan
✅ No critical vulnerabilities found

### Test Coverage
⚠️ 2 files missing tests:
- `src/utils/helper.py`
- `src/services/processor.py`

### Recommendations
1. Add type hints to improve code clarity
2. Add unit tests for new utility functions
3. Consider extracting duplicated logic in processor.py

---
*Generated by AIOps Framework*
"""
    print(comment)

    # In real usage:
    # from github import Github
    # g = Github(os.getenv("GITHUB_TOKEN"))
    # repo = g.get_repo(os.getenv("GITHUB_REPOSITORY"))
    # pr = repo.get_pull(int(os.getenv("PR_NUMBER")))
    # pr.create_issue_comment(comment)


if __name__ == "__main__":
    print("🚀 AIOps GitHub Actions Integration")
    print("="*60)

    # Run the review
    exit_code = asyncio.run(review_pull_request())

    # Post comment (optional)
    # asyncio.run(post_review_comment())

    exit(exit_code)
