"""Example 5: Automated Test Generation

This example demonstrates automatic test generation for improving code coverage.
"""

import asyncio
from pathlib import Path
from aiops.agents.test_generator import TestGeneratorAgent


async def generate_tests_for_file(source_file: str, output_file: str = None):
    """Generate comprehensive tests for a source file."""

    print(f"🧪 Generating Tests for: {source_file}")
    print("="*60)

    # Read source code
    with open(source_file, 'r') as f:
        code = f.read()

    language = Path(source_file).suffix.lstrip('.')

    # Initialize test generator
    test_generator = TestGeneratorAgent()

    # Generate different types of tests
    print("\n📝 Generating Unit Tests...")
    unit_tests = await test_generator.execute(
        code=code,
        language=language,
        test_type="unit",
        framework="pytest"
    )

    print(f"  Generated {unit_tests.total_tests} unit tests")
    print(f"  Estimated coverage: {unit_tests.coverage_estimate}%")

    # Count test types
    normal_tests = sum(1 for tc in unit_tests.test_cases if tc.category == "normal")
    edge_tests = sum(1 for tc in unit_tests.test_cases if tc.category == "edge")
    error_tests = sum(1 for tc in unit_tests.test_cases if tc.category == "error")

    print(f"\n  Test breakdown:")
    print(f"    Normal cases: {normal_tests}")
    print(f"    Edge cases: {edge_tests}")
    print(f"    Error cases: {error_tests}")

    # Show sample tests
    if unit_tests.test_cases:
        print(f"\n  Sample test cases:")
        for test in unit_tests.test_cases[:3]:
            print(f"    - {test.name}")
            print(f"      {test.description}")

    # Generate test file
    if not output_file:
        source_name = Path(source_file).stem
        output_file = f"test_{source_name}.py"

    print(f"\n💾 Saving tests to: {output_file}")

    test_code = generate_test_file(unit_tests, source_file)

    with open(output_file, 'w') as f:
        f.write(test_code)

    print(f"✅ Test file generated successfully!")

    return unit_tests


def generate_test_file(test_suite, source_file: str) -> str:
    """Generate a complete test file from test suite."""

    # Extract module name
    module_name = Path(source_file).stem

    test_code = f'''"""
Automatically generated tests for {module_name}

Generated by AIOps Test Generator
Coverage estimate: {test_suite.coverage_estimate}%
Total tests: {test_suite.total_tests}
"""

import pytest
from {module_name} import *


class Test{module_name.title().replace("_", "")}:
    """Test suite for {module_name}."""

'''

    # Add test methods
    for test_case in test_suite.test_cases:
        test_code += f'''
    def {test_case.name}(self):
        """
        {test_case.description}

        Category: {test_case.category}
        """
        {test_case.code}

'''

    # Add fixtures if needed
    test_code += '''

@pytest.fixture
def sample_data():
    """Sample data for testing."""
    return {
        # Add your test data here
    }


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
'''

    return test_code


async def improve_test_coverage(directory: str, min_coverage: float = 80.0):
    """Improve test coverage for all files in a directory."""

    print(f"📊 Test Coverage Improvement Project")
    print(f"Directory: {directory}")
    print(f"Target coverage: {min_coverage}%")
    print("="*60)

    # Find all Python files
    source_files = [
        f for f in Path(directory).rglob("*.py")
        if not f.name.startswith("test_") and f.name != "__init__.py"
    ]

    print(f"\nFound {len(source_files)} source files\n")

    results = []

    for source_file in source_files:
        print(f"Processing: {source_file.name}")

        # Check if tests exist
        test_file = source_file.parent / f"test_{source_file.name}"

        if test_file.exists():
            print(f"  ⚠️  Tests already exist, analyzing coverage...")
            # In production, use coverage.py to check actual coverage
            current_coverage = 65.0  # Mock value
        else:
            print(f"  ℹ️  No tests found, generating...")
            current_coverage = 0.0

        if current_coverage < min_coverage:
            # Generate tests
            test_suite = await generate_tests_for_file(
                str(source_file),
                str(test_file)
            )

            results.append({
                "file": str(source_file),
                "current_coverage": current_coverage,
                "new_coverage": test_suite.coverage_estimate,
                "tests_generated": test_suite.total_tests,
            })

            print(f"  ✅ Coverage improved: {current_coverage}% → {test_suite.coverage_estimate}%\n")
        else:
            print(f"  ✅ Coverage sufficient: {current_coverage}%\n")

    # Summary
    if results:
        print("\n" + "="*60)
        print("📈 COVERAGE IMPROVEMENT SUMMARY")
        print("="*60)

        total_tests = sum(r["tests_generated"] for r in results)
        avg_improvement = sum(r["new_coverage"] - r["current_coverage"] for r in results) / len(results)

        print(f"\nFiles processed: {len(results)}")
        print(f"Total tests generated: {total_tests}")
        print(f"Average coverage improvement: +{avg_improvement:.1f}%")

        print(f"\nFiles with biggest improvements:")
        top_improvements = sorted(
            results,
            key=lambda x: x["new_coverage"] - x["current_coverage"],
            reverse=True
        )[:5]

        for r in top_improvements:
            improvement = r["new_coverage"] - r["current_coverage"]
            print(f"  {Path(r['file']).name}: +{improvement:.1f}% ({r['tests_generated']} tests)")


async def generate_integration_tests(api_file: str):
    """Generate integration tests for an API."""

    print(f"🌐 Generating Integration Tests for API")
    print("="*60)

    with open(api_file, 'r') as f:
        code = f.read()

    test_generator = TestGeneratorAgent()

    # Generate integration tests
    integration_tests = await test_generator.execute(
        code=code,
        language="python",
        test_type="integration",
        framework="pytest"
    )

    print(f"\nGenerated {integration_tests.total_tests} integration tests")

    # Sample integration test structure
    print(f"\n📝 Sample Integration Test:")
    print("""
    import pytest
    from fastapi.testclient import TestClient
    from main import app

    @pytest.fixture
    def client():
        return TestClient(app)

    @pytest.fixture
    def auth_token(client):
        response = client.post("/auth/token", data={
            "username": "test",
            "password": "test"
        })
        return response.json()["access_token"]

    def test_create_resource(client, auth_token):
        headers = {"Authorization": f"Bearer {auth_token}"}
        response = client.post(
            "/api/resource",
            json={"name": "test"},
            headers=headers
        )
        assert response.status_code == 201
        assert response.json()["name"] == "test"

    def test_get_resource(client, auth_token):
        # Create resource first
        headers = {"Authorization": f"Bearer {auth_token}"}
        create_resp = client.post(
            "/api/resource",
            json={"name": "test"},
            headers=headers
        )
        resource_id = create_resp.json()["id"]

        # Get resource
        get_resp = client.get(
            f"/api/resource/{resource_id}",
            headers=headers
        )
        assert get_resp.status_code == 200
        assert get_resp.json()["name"] == "test"
    """)


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1:
        source_file = sys.argv[1]

        if Path(source_file).is_file():
            # Generate tests for single file
            asyncio.run(generate_tests_for_file(source_file))
        elif Path(source_file).is_dir():
            # Improve coverage for directory
            asyncio.run(improve_test_coverage(source_file))
        else:
            print(f"❌ Invalid path: {source_file}")
    else:
        print("Usage: python 05_test_generation_automation.py <file_or_directory>")
        print("\nExamples:")
        print("  # Generate tests for single file")
        print("  python 05_test_generation_automation.py utils.py")
        print()
        print("  # Improve coverage for entire project")
        print("  python 05_test_generation_automation.py ./src")
